# Name of the workflow. You can give any name
name: StudentManagement API CI

on:
  # Run CI when code is pushed to main or any feature branch
  push:
    branches:
      - master
      - feature/**
      - bugfix/**
  
  # Run CI when a pull request is created or updated for main
  pull_request:
    branches:
      - master

# A job is a group of steps. its internal key name is: build-test-publish
# display name is Build, Test, and Publish which is visible to user
# it will run on a machine which is a Linux machine ubuntu
jobs:
  build-test-publish:
    name: Build, Test, and Publish
    runs-on: ubuntu-latest

    # steps are the works or tasks done inside a job
    steps:
      # Step 1: Download the repository code 
      - name: Checkout source code
        uses: actions/checkout@v5

      # Step 2: Install .NET 10 SDK
      - name: Setup .NET 10 SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      # Step 3: Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore StudentManagement.slnx

      # Step 4: Build the solution in Release mode
      - name: Build solution
        run: dotnet build StudentManagement.slnx --configuration Release --no-restore

      # Step 5: Run unit tests
      - name: Run tests
        run: dotnet test StudentManagement.slnx --configuration Release --no-build --verbosity normal

      # Step 6: Publish the API project
      - name: Publish Web API
        run: dotnet publish StudentManagement/StudentManagement.API.csproj --configuration Release --output ./publish --no-build

      # Step 7: Store the publish output as an artifact
      - name: Upload publish artifact
        uses: actions/upload-artifact@v6
        with:
          name: studentmanagement-api-publish
          path: ./publish